Solution

diff --git a/.github/workflows/reusable-deployment.yml b/.github/workflows/reusable-deployment.yml
--- a/.github/workflows/reusable-deployment.yml
+++ b/.github/workflows/reusable-deployment.yml
@@ -19,56 +19,66 @@ on:
         type: string
 
 jobs:
-    deploy-helm:
-      name: ${{ inputs.environment }}
-      runs-on: ubuntu-latest
-      environment: ${{ inputs.environment }}
+  deploy-helm:
+    name: ${{ inputs.environment }}
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
 
-      steps:
-      - uses: actions/download-artifact@v4
-        with:
-          name: helm-package
-          path: .
+    steps:
+    - uses: actions/checkout@v2
 
-      # Debugging step to confirm artifact download
-      - name: List Files
-        run: ls -alh
+    - uses: actions/download-artifact@v4
+      with:
+        name: helm-package
+        path: .
 
-      - name: Set Up Helm
-        uses: azure/setup-helm@v4.2.0
+    # Debugging step to confirm artifact download
+    - name: List Files in Current Directory
+      run: ls -alh
 
-      - name: Set up Kubectl
-        uses: azure/setup-kubectl@v4
+    # Ensure the cluster.yml file is present
+    - name: Check for cluster.yml
+      run: |
+        if [ ! -f ./cluster.yml ]; then
+          echo "cluster.yml file not found!"
+          exit 1
+        fi
 
-      - name: Create k8s Kind Cluster
-        uses: helm/kind-action@v1
-        with:
-          config: ./cluster.yml
+    - name: Set Up Helm
+      uses: azure/setup-helm@v4.2.0
 
-      - name: Dry Run Helm
-        run: |
-          helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp-*.tgz  \
-          -f ${{ inputs.helm-values-path }} \
-          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
-          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
-          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
-          --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
-          --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
-          --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
-          --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
-          --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
-          --set todoapp.image.tag=${{ github.sha }}
+    - name: Set up Kubectl
+      uses: azure/setup-kubectl@v4
 
-      - name: Deploy helm to Development
-        run: |
-          helm upgrade --install --wait --timeout 180s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
-          -f ${{ inputs.helm-values-path }} \
-          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
-          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
-          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
-          --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
-          --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
-          --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
-          --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
-          --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
-          --set todoapp.image.tag=${{ github.sha }}
+    - name: Create k8s Kind Cluster
+      uses: helm/kind-action@v1
+      with:
+        config: ./cluster.yml
+
+    - name: Dry Run Helm
+      run: |
+        helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp-*.tgz  \
+        -f ${{ inputs.helm-values-path }} \
+        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
+        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
+        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
+        --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
+        --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
+        --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
+        --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
+        --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
+        --set todoapp.image.tag=${{ github.sha }}
+
+    - name: Deploy Helm to Development
+      run: |
+        helm upgrade --install --wait --timeout 180s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
+        -f ${{ inputs.helm-values-path }} \
+        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
+        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
+        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
+        --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
+        --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
+        --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
+        --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
+        --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
+        --set todoapp.image.tag=${{ github.sha }}
